---
- name: Install Vector
  block:
    - name: Create directory vector
      become: true
      ansible.builtin.file:
        path: "{{ vector_path }}"
        state: directory
        mode: 0755

    - name: Get vector distrib
      become: true
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
        dest: "{{ vector_path }}/vector-{{ vector_version }}-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
        mode: 0755

    - name: Unarchive vector distrib
      become: true
      ansible.builtin.unarchive:
        src: "{{ vector_path }}/vector-{{ vector_version }}-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
        dest: "{{ vector_path }}"
        remote_src: true
        creates: "{{ vector_path }}/bin"
        extra_opts: [--strip-components=2]

    - name: Create link
      become: true
      ansible.builtin.file:
        src: "{{ vector_path }}/bin/vector"
        dest: /usr/bin/vector
        owner: root
        group: root
        state: link

    - name: Create vector file
      become: true
      ansible.builtin.template:
        src: "{{ role_path }}/templates/vector.service.j2"
        dest: /etc/systemd/system/vector.service
        mode: 0644
        owner: root
        group: root

    - name: Create config
      become: true
      ansible.builtin.template:
        src: "{{ role_path }}/templates/vector.yaml.j2"
        dest: "{{ vector_config }}"
        owner: root
        group: root
        mode: 0755
        force: true

    - name: Vector.service start
      become: true
      systemd:
        name: vector.service
        state: started
        enabled: true
        daemon_reload: yes
      when: ansible_facts.virtualization_type != "docker"
