---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian
    image: docker.io/pycontribs/debian:latest
    pre_build_image: true
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
